In [22]:
import pandas as pd
from sklearn.ensemble import IsolationForest
import shap # explain about anomaly detection

In [23]:
df=pd.read_csv('Anomaly+-+DBScan.csv')

In [25]:
df=df.select_dtypes(include=["float64","int64"])

In [28]:
df=df.dropna()

In [29]:
df

       Rooms      Price  Postcode  Propertycount  Distance
0          3  1490000.0      3067           4019       3.0
1          3  1220000.0      3067           4019       3.0
2          3  1420000.0      3067           4019       3.0
3          3  1515000.0      3040           1543       7.5
4          2   670000.0      3042           3464      10.4
...      ...        ...       ...            ...       ...
63016      2   347700.0      3199          17055      38.0
63017      3   808000.0      3072          14577       8.4
63018      3   566000.0      3064           5833      20.6
63019      3   500000.0      3064           5833      20.6
63020      3   545000.0      3064           5833      20.6

[48433 rows x 5 columns]

In [3]:
df['Suburb']=df['Suburb'].astype('category')
df['Address']=df['Address'].astype('category')
df['Type']=df['Type'].astype('category')
df['Method']=df['Method'].astype('category')
df['SellerG']=df['SellerG'].astype('category')
df['Date']=pd.to_datetime(df['Date'])
df['Regionname']=df['Regionname'].astype('category')
df['Propertycount']=df['Propertycount'].astype('category')
df['CouncilArea']=df['CouncilArea'].astype('category')

Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.

In [4]:
df['Suburb']=df['Suburb'].cat.codes
df['Address']=df['Address'].cat.codes
df['Type']=df['Type'].cat.codes
df['Method']=df['Method'].cat.codes
df['SellerG']=df['SellerG'].cat.codes
df['Date']=pd.to_datetime(df['Date'])
df['Regionname']=df['Regionname'].cat.codes
df['Propertycount']=df['Propertycount'].cat.codes
df['CouncilArea']=df['CouncilArea'].cat.codes

In [38]:
model=IsolationForest(n_estimators=100,contamination=0.15,random_state=42)

In [17]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Postcode           int64
Regionname        object
Propertycount      int64
Distance         float64
CouncilArea       object
dtype: object

In [18]:
df['Price'].fillna(df['Price'].median(),inplace=True)

In [19]:
df.drop('Date',inplace=True,axis=1)

In [31]:
df.isnull().sum()

Rooms            0
Price            0
Postcode         0
Propertycount    0
Distance         0
dtype: int64

In [39]:
model.fit(df)
# temp_changyuan

X does not have valid feature names, but IsolationForest was fitted with feature names

IsolationForest(contamination=0.15, random_state=42)

In [40]:
anomalies=model.predict(df)

In [1]:
# explainer = shap.KernelExplainer(model.predict,df)
explainer=shap.Explainer(model.predict,df)

In [2]:
# shap_values=explainer.shap_values(df)
s_v=explainer(df)

In [69]:
df.dtypes

Suburb             int16
Address            int32
Rooms              int64
Type                int8
Price            float64
Method              int8
SellerG            int16
Postcode           int64
Regionname          int8
Propertycount      int16
Distance         float64
CouncilArea         int8
dtype: object

In [67]:
df.head(30)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,0,42390,3,0,1490000.0,2,198,3067,2,210,3.0,32
1,0,46855,3,0,1220000.0,2,255,3067,2,210,3.0,32
2,0,8180,3,0,1420000.0,2,286,3067,2,210,3.0,32
3,1,50133,3,0,1515000.0,2,28,3040,6,90,7.5,22
4,2,57182,2,0,670000.0,2,286,3042,6,185,10.4,22
5,2,38897,2,1,530000.0,2,198,3042,6,185,10.4,22
6,2,32208,2,2,540000.0,2,28,3042,6,185,10.4,22
7,2,2499,3,0,715000.0,5,286,3042,6,185,10.4,22
8,3,545,6,0,830000.0,0,454,3021,6,106,14.0,3
9,4,16248,3,0,1925000.0,2,75,3206,5,177,3.0,27
10,5,30903,3,2,515000.0,2,114,3020,6,117,10.5,3
11,5,36965,4,0,717000.0,2,35,3020,6,117,10.5,3
12,6,45968,2,0,1675000.0,2,276,3078,2,119,5.7,6
13,6,40179,4,0,2008000.0,2,198,3078,2,119,5.7,6
14,7,55921,2,0,860000.0,5,27,3018,6,252,11.0,10
15,8,46440,4,0,830000.0,4,28,3028,6,303,15.5,10
16,9,11890,3,0,720000.0,2,181,3025,6,249,9.4,10
17,11,20174,2,2,836000.0,2,198,3143,5,238,6.3,28
18,11,50301,2,0,2110000.0,2,198,3143,5,238,6.3,28
19,11,52603,3,0,1386000.0,2,255,3143,5,238,6.3,28
20,11,12088,2,2,580000.0,7,454,3143,5,238,6.3,28
21,11,48482,1,2,355000.0,2,454,3143,5,238,6.3,28
22,12,54168,3,0,1123100.0,2,346,3032,6,284,4.3,22
23,13,3389,3,2,1270000.0,2,129,3147,5,171,10.2,2
24,13,842,4,0,830000.0,2,198,3147,5,171,10.2,2
25,13,49129,3,1,1610000.0,2,198,3147,5,171,10.2,2
26,14,40687,4,0,1435000.0,2,346,3147,5,159,10.2,21
27,15,37583,4,0,1431000.0,2,454,3195,4,152,21.5,12
28,16,53830,4,0,996000.0,2,346,3195,4,121,21.5,12
29,17,41722,4,0,830000.0,4,28,3049,2,68,16.5,11